### ISSUE TITLE
It doesn't generate random bytes in Android release mode.

### ISSUE THREAD

**Issue by rblcb** [rh389/react-native-securerandom#1]
It works well in android debug mode but doesn't work in android release mode.

**Comment by robhogan** [comment]
Hi, thanks for the report. What’s the problem exactly - what is it returning?

**Comment by rblcb** [comment]
I generated bytes in componentWillMount() function of the component.
Code down below:


  componentWillMount(){
    const thisYear = (new Date()).getFullYear();
    const minOffset = 0;
    const maxOffset = 70;
    const options = [];
    for (let i = minOffset; i <= maxOffset; i++) {
      const year = thisYear - i;
      options.push({'label':year.toString(), 'value':year});
      
    }
    this.setState({
      year:options,
      selectedYearVal:thisYear,
      device_type: Platform.OS,
    })

    //Get Device Token
    generateSecureRandom(12).then(randomBytes => 
      this.setState({device_token: randomBytes.join('')})
    );
    AsyncStorage.multiGet(["X-User-Authorization", 'email', 'password']).then((data) => {
      if(data[0][1]) {
        console.log('X-user--->', data);
        this.props.navigation.navigate('Signup', {...this.state});
      }
    }).done();
  }

It works well in debug mode.
But it returns [object Uint8Array] in release mode especially Android.

**Comment by robhogan** [comment]
It looks like that’s just a problem in the way you’re converting the output to a string (different JS runtimes might differ in how they handle this). 

You probably want to encode the `UInt8Array` (eg in base 64) before you store it in any case, I don’t think `AsyncStorage` is binary safe.

**Comment by robhogan** [comment]
Closing but feel free to ping me if you’re still seeing issues
