### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by olfek** [rh389/react-native-securerandom#2]
react-native-securerandom is not properly linked
PS. I have ran the `link` command

**Comment by rh389** [comment]
Have you linked it? Eg with `react-native link react-native-securerandom`

**Comment by robhogan** [comment]
Which platform? Is the project linked in xcode / showing up in your gradle files?

**Comment by olfek** [comment]
Android, I cant check anymore as I resorted to using Isaac (https://github.com/rubycon/isaac.js)

**Comment by robhogan** [comment]
Ok. Be aware that no pure-JS solution can be cryptographically secure, but if you don't need that then isaac's a fine PRNG.

**Comment by safeer-ahmed** [comment]
Facing the same issue, any resolution to it?
Android: Yes its there in my Gradle files

![WhatsApp Image 2020-07-21 at 11 00 37 AM](https://user-images.githubusercontent.com/15281121/88018597-7daca280-cb41-11ea-9c6a-7f183413cb3e.jpeg)
