### ISSUE TITLE
Question about byte array vs base64

### ISSUE THREAD

**Issue by hadasz** [rh389/react-native-securerandom#4]
Why is it converted from a byte array to base64 array in the native code and then converted from base64 array back to byte array in javascript code? Why not just keep it as a byte array?

Also - great work on this library - it's awesome.

**Comment by hadasz** [comment]
I realize now that it's for compression purposes.

**Comment by robhogan** [comment]
Not compression exactly, just encoding to allow the value to be passed over the react native bridge, which doesn't support transfer of raw byte arrays. And thanks!

**Comment by hadasz** [comment]
Ohh got it, thanks for the clarification!
