### ISSUE TITLE
Android security issue.

### ISSUE THREAD

**Issue by adjicf** [rh389/react-native-securerandom#6]
Hi, it seems that the following affects this module: https://android-developers.googleblog.com/2013/08/some-securerandom-thoughts.html, 
Do we need to add this patch to the code ?
Thanks in advance.

**Comment by robhogan** [comment]
Thanks for raising this. I suspect since that article is dated 2013 that current versions of Android will have this patch built-in, but I'll look into it.

**Comment by rajivshah3** [comment]
> Applications which run exclusively on Android KitKat (4.4) or above do not need to take any special action to work around this bug.

Since this library supports API level 16 (KitKat is 19) it may need to be patched

**Comment by robhogan** [comment]
Quite right, I'd actually forgotten RN's android support still goes back that far. Patch added and published as `0.3.1`

Thanks both.
